### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Mr-GX** [jeasonlzy0216/ImagePicker#11]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
                                                                            at com.lzy.imagepicker.ui.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:60)

**Comment by Mr-GX** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
                                                                            at com.lzy.imagepicker.ui.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:60)
