### ISSUE TITLE
屏幕旋转后的闪退

### ISSUE THREAD

**Issue by JasonHezz** [jeasonlzy0216/ImagePicker#13]
> 

    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lzy.imagepicker.ui.ImageGridActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2551)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2625)
                                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4233)
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:183)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5667)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                                 Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                    at java.util.ArrayList.get(ArrayList.java:308)
                                                                                    at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:116)
                                                                                    at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:19)
                                                                                    at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
                                                                                    at android.support.v4.app.LoaderManagerImpl$LoaderInfo.finishRetain(LoaderManager.java:306)
                                                                                    at android.support.v4.app.LoaderManagerImpl.finishRetain(LoaderManager.java:806)
                                                                                    at android.support.v4.app.FragmentHostCallback.reportLoaderStart(FragmentHostCallback.java:280)
                                                                                    at android.support.v4.app.FragmentController.reportLoaderStart(FragmentController.java:378)
                                                                                    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:608)
                                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)
                                                                                    at android.app.Activity.performStart(Activity.java:6163)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2508)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2625) 
                                                                                    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4233) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:183) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5667) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by jeasonlzy0216** [comment]
0.2.4 以后支持横竖屏切换。。

**Comment by JasonHezz** [comment]
感谢修复!
