### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by JasonHezz** [jeasonlzy0216/ImagePicker#2]
`   Process: com.lzy.imagepickerdemo, PID: 12185
                                                                         java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=1004, data=Intent {  }} to activity {com.lzy.imagepickerdemo/com.lzy.imagepickerdemo.ImagePickerActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:3845)
                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:3888)
                                                                             at android.app.ActivityThread.access$1300(ActivityThread.java:178)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                             at android.os.Looper.loop(Looper.java:194)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5643)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                                                                             at com.lzy.imagepickerdemo.ImagePickerActivity$MyAdapter.getCount(ImagePickerActivity.java:210)
                                                                             at android.widget.GridView.setAdapter(GridView.java:206)
                                                                             at com.lzy.imagepickerdemo.ImagePickerActivity.onActivityResult(ImagePickerActivity.java:188)
                                                                             at android.app.Activity.dispatchActivityResult(Activity.java:6302)
                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:3841)
                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:3888) 
                                                                             at android.app.ActivityThread.access$1300(ActivityThread.java:178) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                             at android.os.Looper.loop(Looper.java:194) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5643) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)`
![image](https://cloud.githubusercontent.com/assets/15358765/14448020/8c311ae4-0097-11e6-8217-0a7af13fde2a.png) 应该是没有检查images是否为空

**Comment by jeasonlzy0216** [comment]
嗯 这个是 demo 里面的用法。。可能没有检查。。库应该是没有问题的。。
