### ISSUE TITLE
在三星手机上调用拍照崩溃，崩溃日志如下

### ISSUE THREAD

**Issue by haonan1** [jeasonlzy0216/ImagePicker#35]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x4000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1727)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1511)
	at android.app.Activity.startActivityForResult(Activity.java:3424)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
	at android.app.Activity.startActivityForResult(Activity.java:3385)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:871)
	at com.lzy.imagepicker.ImagePicker.takePicture(ImagePicker.java:255)
	at com.lzy.imagepicker.adapter.ImageGridAdapter$1.onClick(ImageGridAdapter.java:107)
	at android.view.View.performClick(View.java:4499)
	at android.view.View$PerformClick.run(View.java:18575)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5021)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by nanchen2251** [comment]
请再测试一下新版本
